src/test/ArbitraryDerivingSuite.scala, src/test/test_classes.scala
Add two test cases that document the current inlining limits of derivation. (Mainly to guard against accidental worsening by refactoring.)
=> test: add tests that document inlining limits

src/main/derived/ArbitraryDeriving.scala, src/test/ArbitraryDerivingSuite.scala, src/test/test_classes.scala
Refactor derivation of Arbitrary-instances so that it is (much) more likely that in case of "Maximal number of successive inlines exceeded", the compiler error message will be the expected one.
This change is somewhat breaking as it increases the inlining steps for products by one, so it slightly reduces the threshold for hitting that limit. (This could have been avoided at the price of writing redundant code, but that didn't seem worth it.)
=> fix!: non-helpful max inlines error messages

src/main/derived/macros.scala
Apparently, `import quotes.reflect.*` is the common way to do this.
=> chore: use common syntax for Quotes.reflect.*

src/main/derived/ArbitraryDeriving.scala, src/main/derived/CogenDeriving.scala, src/main/derived/ShrinkDeriving.scala, src/main/derived/derived.scala, src/test/ArbitraryDerivingSuite.scala, src/test/CogenDerivingSuite.scala, src/test/ShrinkDerivingSuite.scala, src/test/test_classes.scala
This is somewhat breaking because it adds 1-2 further inlining step(s) to derivation (1 for Arbitrary and Cogen, 2 for Shrink), thus increasing the risk to hit Xmaxinlines.
=> feat!: support for recursive structures

src/main/derived/ArbitraryDeriving.scala, src/test/ArbitraryDerivingSuite.scala, src/test/CogenDerivingSuite.scala, src/test/ShrinkDerivingSuite.scala, src/test/test_classes.scala
fixes that recursive structures could lead to an infinite loop at runtime if the very first field of a product would recur to the "parent" sum (because of a lack of lazyness).
=> fix: direct recursion

src/main/derived/ArbitraryDeriving.scala, src/main/derived/CogenDeriving.scala, src/main/derived/ShrinkDeriving.scala, src/test/ArbitraryDerivingSuite.scala, src/test/CogenDerivingSuite.scala, src/test/ShrinkDerivingSuite.scala, src/test/test_classes.scala
Fixes that the explicit derivation functions (`deriveArbitrary`, `deriveCogen`, `deriveShrink`) would not use existing givens if those depend on a given that needs to be derived (e.g. not using `arbContainer[C, T]` if the required `Arbtrirary[T]` needs to be derived).
=> fix: explicit derivation not using some givens

.github/workflows/ci.yml, src/test/conf.scala
Turns out that the tests (which so far were not run in CI for scala-native and scala-js) were broken for scala-native by the bump to munit 1.0.0-M10.
So for now, this downgrades the munit version back to 1.0.0-M9 and enables tests for native and js in CI.
=> fix: munit 1.0.0-M10 breaking scala-native tests

project.scala, src/test/conf.scala
Now that scala-cli support syntax for declaration of test-dependencies, there's no more need to declare them separately in the test-dir.
=> chore: move declaration of test-dependencies

project.scala
Bumps scalacheck to 1.18.0 to obtain support
for scala-native 0.5.x
Also bumps jsVersion to 1.16.0 because that's
what scalacheck 1.18.0 is compiled against.
=> feat: scala-native 0.5.x / scalacheck 1.18.0

build.sbt
(Fixes that an empty 2.12 artifact was published.)
=> build: skip publishing of root

.jvmopts, build.sbt, core/src/main/scala/io/github/martinhh/derived/ArbitraryDeriving.scala, core/src/main/scala/io/github/martinhh/derived/derived.scala, core/src/test/scala/io/github/martinhh/ArbitraryDerivingSuite.scala, core/src/test/scala/io/github/martinhh/CogenDerivingSuite.scala, core/src/test/scala/io/github/martinhh/ShrinkDerivingSuite.scala, core/src/test/scala/io/github/martinhh/test/ArbitrarySuite.scala, core/src/test/scala/io/github/martinhh/test/CogenSuite.scala, core/src/test/scala/io/github/martinhh/test/ShrinkSuite.scala, extras/src/main/scala/io/github/martinhh/derived/extras/LiteralArbitraries.scala, extras/src/main/scala/io/github/martinhh/derived/extras/TypedTypeClass.scala, extras/src/main/scala/io/github/martinhh/derived/extras/UnionArbitraries.scala, extras/src/main/scala/io/github/martinhh/derived/extras/UnionCogens.scala, extras/src/main/scala/io/github/martinhh/derived/extras/UnionShrinks.scala, extras/src/main/scala/io/github/martinhh/derived/extras/api.scala, extras/src/main/scala/io/github/martinhh/derived/extras/macros.scala, extras/src/test/scala/io/github/martinhh/ExtrasSuite.scala
- Arbitrary instances for literal types
- Arbitrary, Shrink and Cogen instances for union types
=> feat: instances for literal and union types

core/src/main/scala/io/github/martinhh/derived/ArbitraryDeriving.scala, core/src/main/scala/io/github/martinhh/derived/macros.scala, core/src/test/scala/io/github/martinhh/ArbitraryDerivingSuite.scala, core/src/test/scala/io/github/martinhh/test_classes.scala
Filter out duplicate instances of Gens that can result from diamond inheritance in sealed trait (which would lead to extra weight on the affected types).
Fixes #79
=> fix: uneven distribution #79

core/src/main/scala/io/github/martinhh/derived/ShrinkDeriving.scala
Fix some warnings that would be issued when changing scala version to 3.6.3
=> chore: minor code cleanup

core/src/main/scala/io/github/martinhh/derived/ShrinkDeriving.scala, core/src/test/scala/io/github/martinhh/test_classes.scala, extras/src/main/scala/io/github/martinhh/derived/extras/union/UnionShrinks.scala
Use "cat:" instead of "msg:" to suppress
deprecation warnings for Stream.
Also: annotate each affected method,
not whole trait.
=> refactor: rearrange @nowarn

build.sbt, core/src/main/scala/io/github/martinhh/derived/ShrinkDeriving.scala, core/src/test/scala/io/github/martinhh/test/ShrinkSuite.scala, core/src/test/scala/io/github/martinhh/test_classes.scala
Fix deprecations of Stream (as used by Shrink) spreading all over the generated code due to @nowarn having no effect on inlined methods.
(Fixed by hiding the deprecated stuff in a non-inlined helper.)
=> fix: leaking Shrink-related deprecations

docs/extras.md
Assuming this is the correct dependency
https://central.sonatype.com/artifact/io.github.martinhh/scalacheck-derived-extras_3
=> chore: fix typo in `extras.md`

README.md, core/src/main/scala/io/github/martinhh/derived/ArbitraryDeriving.scala, core/src/main/scala/io/github/martinhh/derived/RecursionFallback.scala, core/src/test/scala/io/github/martinhh/ArbitraryDerivingSuite.scala, core/src/test/scala/io/github/martinhh/test/ArbitrarySuite.scala, core/src/test/scala/io/github/martinhh/test_classes.scala, docs/recursive.md
Provide means to configure a Gen that will terminate a recursion.
(Follow-up to the fix for #104 )
=> feat: RecursionFallback

.github/workflows/ci.yml, .github/workflows/release.yml
(to re-enable publishing)
Mitigates https://github.com/xerial/sbt-sonatype/issues/518
=> ci: bump java to 11

core/src/main/scala/io/github/martinhh/derived/ArbitraryDeriving.scala, core/src/test/scala/io/github/martinhh/ArbitraryDerivingSuite.scala, core/src/test/scala/io/github/martinhh/test_classes.scala
Fixes that `RecursionFallback` instance were never in scope at the place where the derived code would look for them.
Resolves #113
=> fix: RecursionFallback not in implicit scope

core/src/main/scala/io/github/martinhh/derived/ArbitraryDeriving.scala, core/src/main/scala/io/github/martinhh/derived/RecursionFallback.scala, core/src/main/scala/io/github/martinhh/derived/api.scala, core/src/test/scala/io/github/martinhh/ConfiguredArbitraryDerivingSuite.scala
Allow to override the logic for combining the `Gen` instances for a sum-type so that users can override the default `Gen.sized`-based solution.
Closes #108 (as that scenario could now be mitigated via a customized solutions).
=> feat: allow custom sum-gen logic

README.md
Migrate badge to maven-central. 
For now, this will use a fixed version as automatic resolution of the latest version fails.
=> docs: update maven badge

core/src/main/scala/io/github/martinhh/derived/ArbitraryDeriving.scala, core/src/test/scala/io/github/martinhh/ArbitraryDerivingSuite.scala
Alternative derivation API where derivation will abort if instances for members of product types
are not available (instead of deriving them).
(However: it will derive the subtypes of a sum type if that is possible without deriving members of those.)
Not exactly what was requested in #133 , but it goes in that direction.
=> feat: deriveArbitraryShallow

core/src/main/scala/io/github/martinhh/derived/ArbitraryDeriving.scala, core/src/main/scala/io/github/martinhh/derived/CogenDeriving.scala, core/src/main/scala/io/github/martinhh/derived/ShrinkDeriving.scala, extras/src/main/scala/io/github/martinhh/derived/extras/literal/LiteralArbitraries.scala, extras/src/main/scala/io/github/martinhh/derived/extras/literal/LiteralCogens.scala, extras/src/main/scala/io/github/martinhh/derived/extras/union/UnionArbitraries.scala, extras/src/main/scala/io/github/martinhh/derived/extras/union/UnionCogens.scala, extras/src/main/scala/io/github/martinhh/derived/extras/union/UnionShrinks.scala
Reverting #122 and the similar changes from #121 for now as there is still at least one bug in the mechanism introduced in #121 - so I'd rather not make it public in the upcoming release (and just making some of the traits public but not the main one seems inconsistent).
=> chore: disallow inheritance of APIs

.github/workflows/ci.yml
workaround for https://github.com/actions/runner-images/issues/12435
(which causes compilation errors for scala native on windows machines).
=> ci: fix native builds on windows

core/src/main/scala/io/github/martinhh/derived/ArbitraryDeriving.scala, core/src/main/scala/io/github/martinhh/derived/CogenDeriving.scala, core/src/main/scala/io/github/martinhh/derived/ShrinkDeriving.scala, extras/src/main/scala/io/github/martinhh/derived/extras/literal/LiteralArbitraries.scala, extras/src/main/scala/io/github/martinhh/derived/extras/literal/LiteralCogens.scala, extras/src/main/scala/io/github/martinhh/derived/extras/union/UnionArbitraries.scala, extras/src/main/scala/io/github/martinhh/derived/extras/union/UnionCogens.scala, extras/src/main/scala/io/github/martinhh/derived/extras/union/UnionShrinks.scala
Make the various "API-traits" public so one can mix them into test suites etc.
This was already implemented in #122, but then reverted before the 0.9.0 release in #140 to exclude it from that release in order to fix a bug that affected "configured derivation for sum-types" (which depends on inheritance). That bug was not fixed (#150), so inheritance and thus configured derivation (#121) can be made public in the next release.
=> feat: allow inheritance of APIs

README.md
Reverts MartinHH/scalacheck-derived#157 due to the fix for https://github.com/softwaremill/maven-badges/issues/1009#issuecomment-3023914171 being reverted.
=> docs: restore badge version param
